### ISSUE TITLE
GTD algorithm implementation

### ISSUE THREAD

**Issue by Amir-19** [rldotai/rl-algorithms#1]
I was reading the GTD implementation and I got a little confused about updating the weights. Based on the code these are the update rules.
```
        self.w += alpha*(delta*self.e + gm_p*(1-lm_p)*np.dot(self.e, self.h)*xp)
        self.h += beta*(delta*self.e + np.dot(self.h, x)*x)
```
However, based on Maei's thesis the update rules are a little different.
```
        self.w += alpha*(delta*self.e - gm_p*(1-lm_p)*np.dot(self.e, self.h)*xp)
        self.h += beta*(delta*self.e - np.dot(self.h, x)*x)
```
![screen shot 2018-06-09 at 6 56 51 pm](https://user-images.githubusercontent.com/23201192/41197340-2d0481b2-6c17-11e8-9a79-3ab8376c1f24.png)
Is there a reason for these differences?

**Comment by rldotai** [comment]
That looks like an error on my part. 
I referred to code that I'd already written when I was benchmarking these algorithms ([for example](https://github.com/rldotai/rlbench/blob/master/rlbench/algos.py)) but presumably made a typo.

I'll fix that and add some tests to make sure everything else works.
Thanks for point that out!
